#!/usr/bin/env zsh

# Switch the font in Alacritty configuration

ALACRITTY_CONFIG="$HOME/.config/alacritty/alacritty.toml"

# Check arguments
if [[ $# -eq 0 ]]; then
    FONT_NAME=$(fc-list : family | grep -i "nerd font" | grep -v " Mono" | grep -v " Propo" | cut -d',' -f1 | sort -u | fzf --prompt="Select font: ")
    if [[ -z "$FONT_NAME" ]]; then
        echo "❌ No font selected"
        exit 1
    fi
    FONT_SIZE="12.0"
else
    FONT_NAME="$1"
    FONT_SIZE="${2:-12.0}"
fi

# Validate font exists
if ! fc-list : family | grep -qF "$FONT_NAME"; then
    echo "❌ Error: Font '$FONT_NAME' not found!"
    echo
    echo "Available fonts:"
    fc-list : family | grep -i "nerd font" | grep -v " Mono" | grep -v " Propo" | cut -d',' -f1 | sort -u | sed 's/^/  - /'
    echo
    echo "💡 Tip: Font names are case-sensitive"
    echo "💡 Run ./list-fonts.sh to see all available fonts"
    exit 1
fi

# Ensure config file exists
if [[ ! -f "$ALACRITTY_CONFIG" ]]; then
    echo "⚠️  Alacritty config not found, creating new one..."
    mkdir -p "$(dirname "$ALACRITTY_CONFIG")"
    cat > "$ALACRITTY_CONFIG" <<EOF
# Alacritty Configuration
# Auto-generated by fonts-cli

[font]
size = $FONT_SIZE

[font.normal]
family = "$FONT_NAME"
EOF
    echo "✅ Created $ALACRITTY_CONFIG"
    echo "✅ Font set to: $FONT_NAME (size: $FONT_SIZE)"
    exit 0
fi

# Update existing config
# Check if [font] section exists
if grep -q '^\[font\]' "$ALACRITTY_CONFIG"; then
    # [font] section exists
    
    # Check if size is set
    if grep -q '^size[[:space:]]*=' "$ALACRITTY_CONFIG"; then
        # Update size
        sed -i.bak "s/^size[[:space:]]*=.*/size = $FONT_SIZE/" "$ALACRITTY_CONFIG"
    else
        # Add size after [font] line
        sed -i.bak "/^\[font\]/a\\
size = $FONT_SIZE
" "$ALACRITTY_CONFIG"
    fi
    
    # Check if [font.normal] section exists
    if grep -q '^\[font\.normal\]' "$ALACRITTY_CONFIG"; then
        # Update family in [font.normal]
        sed -i.bak "/^\[font\.normal\]/,/^\[/s/^family[[:space:]]*=.*/family = \"$FONT_NAME\"/" "$ALACRITTY_CONFIG"
    else
        # Add [font.normal] section after [font] block
        # Find the next section after [font] or end of file
        awk -v font="$FONT_NAME" '
        BEGIN {in_font=0; added=0}
        /^\[font\]/ {in_font=1; print; next}
        /^\[/ && in_font && !added {
            print ""
            print "[font.normal]"
            print "family = \"" font "\""
            print ""
            in_font=0
            added=1
        }
        {print}
        END {
            if (in_font && !added) {
                print ""
                print "[font.normal]"
                print "family = \"" font "\""
            }
        }
        ' "$ALACRITTY_CONFIG" > "${ALACRITTY_CONFIG}.tmp"
        mv "${ALACRITTY_CONFIG}.tmp" "$ALACRITTY_CONFIG"
    fi
else
    # No [font] section, add it at the end
    cat >> "$ALACRITTY_CONFIG" <<EOF

[font]
size = $FONT_SIZE

[font.normal]
family = "$FONT_NAME"
EOF
fi

# Clean up backup file
rm -f "${ALACRITTY_CONFIG}.bak"

# Touch config to trigger reload
touch "$ALACRITTY_CONFIG"

echo "✅ Font switched to: $FONT_NAME"
echo "   Size: $FONT_SIZE"
echo
echo "💡 Alacritty should auto-reload. If not, reopen the terminal."
